---
# The size of the pattern, not including the L seed
pattern_size : 4

# A <pattern_size> X <pattern_size> 2D array
# This field can be null
pattern : null

# Use a random pattern instead of the pattern above
random_pattern : True

# Amount of genes in each generation
gene_count : 25

# Mutation rate of each gene, 1 in <mutation_rate> chance
mutation_rate : 4